### PR TITLE
Decrease docker size

### PR DESCRIPTION
**Pull request by DeviaVir**
@pebble/webops

### CODE REVIEW

**Comment by DeviaVir** [comment]
screen shot 2016-05-02 at 15 15 21

**Comment by thepwagner** [comment]
+1; you could use `pip install https://github.com/pebble/cloudwatch-mon-scripts-python/tarball/master\#egg\=cloudwatchmon-2.0.3` to avoid doing the hokey pokey with git and overhead of a full clone during the build. Meh.

**Comment by DeviaVir** [comment]
@thepwagner saving the git overhead seems worth it, updated

**Comment by lrvick** [comment]
+1

**Pull request merged**
